### PR TITLE
Update/devops 4182

### PR DESCRIPTION
**Pull request by Jkinville**
1.0 of our GitHub account policy and first piece of new policy in a long time

### CODE REVIEW

**Review by sbarthelmess — COMMENTED** [review]
The content looks good.  I recommend we subreference just the policy section as a best practice, in case we have to reference an explicit part of the policy during an infraction or for reference.  For instance, "please refer to section 4.6 of the Github-Account-Policy as you have 24 hours to comply".

**Review by jamiepeloquin — APPROVED** [review]
👍 Looks great!

**Comment by kellyuehling** [comment]
Not being a github pro by any means, the environment is a bit foreign but I can certainly see the potential. Looks great!

**Review by sbarthelmess — APPROVED** [review]
Perfect to get this thing off the ground!  Happy merging.

**Review by DougC-Newforma — APPROVED** [review]

**Pull request merged**
